steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - apps/workspace-server/Dockerfile
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1800s
