import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { FlowNode } from "../model/Program.js";
import { FlowWalker } from "./FlowWalker.js";

/**
 * Generates `src/model/generated/prompt.ts` from Halo's source: the send
 * flow, starting at Editor.handleKeyDown, for comparison with the
 * hand-written flow in `halo.ts`.
 */

const packageRoot = path.resolve(
  fileURLToPath(new URL("..", import.meta.url)),
  "..",
);
const repoRoot = path.resolve(packageRoot, "..", "..");

const walker = FlowWalker.create({
  repoRoot,
  tsconfig: "apps/electron/tsconfig.json",
  extraRoots: ["packages/server/src/router.ts"],
  ignore: ["packages/logger/"],
  packageServices: [
    {
      prefix: "@earendil-works/",
      service: "pi",
      name: "Pi",
      carrier: "memory",
    },
  ],
  rpc: {
    clientPackage: "@orpc/client",
    routerFile: "packages/server/src/router.ts",
    routerExport: "haloRpcRouter",
    carrier: "rpc",
    from: "renderer",
    to: "main",
  },
  refHelpers: ["useRefCurrent"],
  callbackSites: [{ component: "Composer", within: "AgentPane" }],
  sinks: [
    {
      pathIncludes: "@types/node/fs",
      service: "disk",
      name: "Disk",
      carrier: "filesystem",
    },
  ],
});
if (walker instanceof Error) {
  console.error(walker.message);
  process.exit(1);
}

const result = walker.walkFrom({
  file: "apps/electron/src/renderer/main/agent/Editor.tsx",
  line: 93,
  process: "renderer",
  trigger: {
    from: "human",
    name: "Cmd/Ctrl+Enter in the composer",
    carrier: "ui",
  },
});
if (result instanceof Error) {
  console.error(result.message);
  process.exit(1);
}

const output = `// Generated by \`pnpm --filter @get-halo/flowstack generate\`. Do not edit.
import type { Flow, Service } from "../Program.js";

export const generatedPromptServices: Service[] = ${JSON.stringify(result.services, undefined, 2)};

export const generatedPromptFlow: Flow = {
  id: "promptGenerated",
  title: "Send a prompt (generated)",
  description:
    "Walked from Editor.handleKeyDown by src/walker/FlowWalker.ts, for a prompt in an open session. Plain calls resolve through the type checker; if/else and returns come along as branches and guards; rules cover React callback props, oRPC client to router with the reply, TanStack query invalidation, node:fs as the disk, and Pi as a service.",
  children: ${JSON.stringify([result.root], undefined, 2)},
};
`;
await writeFile(
  path.join(packageRoot, "src/model/generated/prompt.ts"),
  output,
);

console.log(render(result.root, ""));
console.log(`\nomitted calls (${result.omitted.length}):`);
for (const entry of result.omitted) {
  console.log(`  ${entry.callee}  ${entry.where}  — ${entry.reason}`);
}
console.log(`\nunresolved (${result.unresolved.length}):`);
for (const entry of result.unresolved) console.log(`  ${entry}`);

function render(node: FlowNode, indent: string): string {
  const label =
    node.kind === "event"
      ? `${node.name}  [${node.carrier}]`
      : node.kind === "reply"
        ? `↩ ${node.value}  [${node.carrier}]`
        : node.kind === "frame"
          ? `${node.entry}  ${node.source === undefined ? "" : `${node.source.path}:${node.source.start}-${node.source.end}`}`
          : node.label;
  const at = node.at === undefined ? "" : `  @${node.at}`;
  const guards =
    node.guards === undefined ? "" : `  {${node.guards.join(" · ")}}`;
  return [
    `${indent}${label}${at}${guards}`,
    ...node.children.map((child) => render(child, `${indent}  `)),
  ].join("\n");
}
